apiVersion: v2
name: wazuh
description: Wazuh is a free and open source security platform that unifies XDR and SIEM protection for endpoints and cloud workloads.
type: application
appVersion: 4.12.0
version: 0.3.2
annotations:
  artifacthub.io/prerelease: "false"
  artifacthub.io/category: security
  artifacthub.io/changes: |
    - kind: changed
      description: "Update all components to Wazuh 4.12.0"
    - kind: changed
      description: "Update agent image to 4.12.0"
    - kind: added
      description: "Add ARM architecture support via nodeSelector"
    - kind: added
      description: "Add support for cert-manager"
    - kind: changed
      description: "Refactor whole chart"
  artifacthub.io/links: |
    - name: application source
      url: https://github.com/wazuh/wazuh
    - name: kustomize source
      url: https://github.com/wazuh/wazuh-kubernetes
  artifacthub.io/screenshots: |
    - title: Home Page
      url: https://morgoved.github.io/wazuh-helm/images/dashboard.png
    - title: Agent Deployment
      url: https://morgoved.github.io/wazuh-helm/images/agent-deploy.png
    - title: Threat Hunting
      url: https://morgoved.github.io/wazuh-helm/images/threat-hunting.png
home: https://wazuh.com/
sources:
  - https://github.com/morgoved/wazuh-helm
maintainers:
  - name: Morgoved
    email: morgyes@gmail.com
    url: https://github.com/morgoved
  - name: Kaslie
    email: jinyi_lie@yahoo.com
    url: https://github.com/Kaslie
  - name: Dani
    email: andre.gomes@promptlyhealth.com
    url: https://github.com/Ca-moes
  - name: TrueDru
    url: https://github.com/TrueDru
  - name: 71g3pf4c3
    url: https://github.com/71g3pf4c3
icon: https://morgoved.github.io/wazuh-helm/images/icon.png
keywords:
  - security
  - information
  - threat
  - management
  - kubernetes
  - wazuh
  - opendistro
  - elasticsearch
dependencies:
  - name: cert-manager
    version: 1.18.1
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled
