{{- if .Values.indexer.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wazuh.indexer.fullname" . }}-indexer-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "wazuh.indexer.fullname" . }}-indexer
  annotations:
    {{- toYaml .Values.indexer.annotations | nindent 4 }}
data:
  internal_users.yml: |
    {{- tpl .Values.indexer.config.internalUsers . | nindent 4 }}
  opensearch.yml: |
    {{- tpl .Values.indexer.config.opensearch . | nindent 4 }}
  roles_mapping.yml: |
    {{- tpl .Values.indexer.config.rolesMapping . | nindent 4 }}
  roles.yml: |
    {{- tpl .Values.indexer.config.roles . | nindent 4 }}
  config.yml: |
    {{- tpl .Values.indexer.config.securityConfig . | nindent 4 }}
{{- range $configName, $configYaml := .Values.indexer.additionalConfigs }}
  {{ $configName }}: |
    {{-   tpl $configYaml . | nindent 4 }}
{{- end -}}
{{- end }}
